name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean compile assembly:single
    - uses: actions/upload-artifact@v1
      with:
        name: MIDI-Studio_Linux
        path: target

  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean compile assembly:single
    - uses: actions/upload-artifact@v1
      with:
        name: MIDI-Studio_Windows
        path: target

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn clean compile assembly:single
    - uses: actions/upload-artifact@v1
      with:
        name: MIDI-Studio_macOS
        path: target
