name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Check Maven dependencies update
      run: mvn -B versions:display-dependency-updates
    - name: Compile with Maven
      run: mvn -B compile
    - name: Build with Maven
      run: mvn -B javafx:jlink
    - name: Package with Maven
      run: mvn package
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}
        path: target
