name: Build with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java_version: [11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Check Maven dependencies update
      run: mvn -B versions:display-dependency-updates
    - name: Compile with Maven
      run: mvn -B compile
    - name: Build with Maven
      run: mvn -B javafx:jlink
    - name: Package with Maven
      run: mvn package
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.java_version }}
        path: target
